<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Book;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'id' => 1,
                'title' => "Le monde confisqué",
                'subtitle' => "Essai sur le capitalisme de la finitude (XVIe - XXIe siècle)",
                'authors' => "Arnaud Orain",
                'summary' => "<p>L&#039;utopie néolibérale d’une croissance globale et continue des richesses est désormais derrière nous. Mais le capitalisme n’est pas mort pour autant. Sa forme actuelle n’est ni réellement nouvelle ni totalement inconnue, car elle est propre à tous les âges où domine le sentiment angoissant d’un monde « fini », borné et limité, qu’il faut s’accaparer dans la précipitation. Ce capitalisme se caractérise par la privatisation et la militarisation des mers, un « commerce » monopolistique et rentier qui s’exerce au sein d’empires territoriaux, l’appropriation des espaces physiques et cybers par de gigantesques compagnies privées aux prérogatives souveraines, qui dictent leurs rythmes.</p><p>Dans cet essai, Arnaud Orain dévoile ce « capitalisme de la finitude » et en éclaire les mécanismes aux trois périodes où il s’épanouit : XVIᵉ - XVIIIᵉ siècle, 1880-1945, 2010 à nos jours. L’auteur offre une toute nouvelle perspective sur l’histoire mondiale et éclaire les grands enjeux de notre temps.</p>",
                'publication_date' => "2025-01-22",
                'isbn' => null,
                'publisher_id' => 1,
                'link' => "https://editions.flammarion.com/le-monde-confisque/9782080466570",
                'image' => "http://atdc4.test/storage/images/books/69ac839069f64.png",
                'created_at' => "2026-03-07 19:59:12.000",
                'updated_at' => "2026-03-07 19:59:12.000"
            ],
            [
                'id' => 2,
                'title' => "Grands ensemble",
                'subtitle' => "Violence, solidarité et ressentiment dans les quartiers populaires",
                'authors' => "Gérôme Truc, Fabien Truong",
                'summary' => "<p>Un livre de plus sur la banlieue ? Pour dénoncer son &quot; communautarisme &quot; et son &quot; séparatisme &quot; ? Pour célébrer sa &quot; diversité &quot; et son &quot; dynamisme &quot; ? Non. À rebours des clichés, une enquête patiente menée pendant dix ans par Fabien Truong et Gérôme Truc dans la foulée des attentats de 2015, à Grigny, ville &quot; la plus pauvre de France &quot; – qui est aussi celle du &quot; terroriste de l&#039;Hyper Cacher &quot;.</p><p>Au plus près des personnes et des faits, Grands ensemble éclaire d&#039;un nouveau jour le rapport des quartiers populaires aux attentats islamistes et, de là, la vie ordinaire de leurs habitantes et habitants, à l&#039;épreuve des violences qui pèsent structurellement sur leur quotidien : celles des trafics et de la police, mais aussi de l&#039;exploitation, de la pauvreté, du racisme, du virilisme et de la stigmatisation. À l&#039;épreuve aussi des blessures intimes et des combats communs.</p><p>Comment tient-on dans ces conditions ? Qu&#039;induit le fait de vivre en se sachant scruté par les médias, pointé du doigt quand un voisin bascule dans le terrorisme ? Pourquoi les conditions de vie dans ces quartiers ne cessent-elles de se dégrader, alors qu&#039;une large part de leur population parvient à trouver sa place dans la société ?</p><p>Les réponses apportées ici épousent le rythme et les contours de multiples trajectoires entrecroisées. Des vies qui rappellent que la pauvreté et la marginalisation engendrent solidarités mais aussi rivalités, pavant la voie à un rapport au monde où le ressentiment coexiste avec l&#039;espoir et la joie.</p>",
                'publication_date' => "2025-01-23",
                'isbn' => null,
                'publisher_id' => 2,
                'link' => "https://www.editionsladecouverte.fr/grands_ensemble-9782348072819",
                'image' => "http://atdc4.test/storage/images/books/69ac850de3c81.png",
                'created_at' => "2026-03-07 20:05:02.000",
                'updated_at' => "2026-03-07 20:05:33.000"
            ],
            [
                'id' => 3,
                'title' => "Le Puy du Faux",
                'subtitle' => "Enquête sur un parc qui déforme l'Histoire",
                'authors' => "Florian Besson, Guillaume Lancereau, Pauline Ducret, Mathilde Larrère",
                'summary' => "<p>Le Puy du Fou séduit chaque année deux millions de personnes. Prenant ce succès au sérieux, quatre historiens et historiennes se sont immergés dans le parc, ont assisté à tous les spectacles et frissonné avec le public. Ils livrent ici une enquête minutieuse et pleine d’humour où apparaît, derrière les effets spéciaux et les décors somptueux, un univers rempli d’erreurs et de simplifications, le tout au service d’une propagande diffuse qu’il s’agit de repérer si on veut la combattre.</p>",
                'publication_date' => "2022-03-24",
                'isbn' => null,
                'publisher_id' => 3,
                'link' => "https://arenes.fr/livre/le-puy-du-faux/",
                'image' => "http://atdc4.test/storage/images/books/69ac8601ac502.png",
                'created_at' => "2026-03-07 20:09:37.000",
                'updated_at' => "2026-03-07 20:09:37.000"
            ],
            [
                'id' => 4,
                'title' => "La haine des fonctionnaires",
                'subtitle' => null,
                'authors' => "Julie Gervais, Claire Lemercier, Willy Pelletier",
                'summary' => "<p>Tout le monde connaît l’équation : fonctionnaires = feignasses = pas rentables = emmerdeurs = protégés = profiteurs = archaïques = inutiles = à compresser. D’où vient son incroyable puissance d’évidence ? Et quels intérêts sert-elle ? Pourquoi certains (hauts) fonctionnaires comptent-ils parmi ceux qui la répètent le plus ? Pourquoi autant d’insultes contre celles et ceux qui voudraient servir le public en toute égalité, et si peu envers les actionnaires, les employeurs ou les pollueurs ?</p><p>Pour répondre à ces questions, ce livre part d’idées reçues, de scènes de la vie quotidienne et de stéréotypes. Nous entraînant dans les coulisses de la fonction publique, il dévoile les réalités vécues par les agents de ménage, les ouvriers des voiries, les secrétaires de mairie, les enseignants, les gardiens de prison et bien d’autres. Le dénigrement des fonctionnaires n’est en réalité qu’un prétexte à la détérioration accélérée des services publics. Ainsi, pour l’ensemble des usagers qui souffrent de leur disparition, pour celles et ceux qui en ont assez qu’on stigmatise ces métiers, il s’agit de ne pas se tromper de cibles et d’organiser la riposte : il en va de notre bien commun.</p>",
                'publication_date' => "2026-03-07",
                'isbn' => null,
                'publisher_id' => 4,
                'link' => "https://www.editionsamsterdam.fr/la-haine-des-fonctionnaires/",
                'image' => "http://atdc4.test/storage/images/books/69ac869e40eb0.png",
                'created_at' => "2026-03-07 20:12:14.000",
                'updated_at' => "2026-03-07 20:12:14.000"
            ],
            [
                'id' => 5,
                'title' => "Un historien à Gaza",
                'subtitle' => null,
                'authors' => "Jean-Pierre Filiu",
                'summary' => "<p>&quot; Vous avez voulu l&#039;enfer, vous aurez l&#039;enfer. &quot;</p><p>C&#039;est en ces termes que l&#039;armée israélienne a déclenché sa guerre contre la bande de Gaza après les attentats du 7 octobre 2023. Une guerre qui, malgré sa violence, sa durée et ses répercussions planétaires, se déroule à huis clos. Aucun journaliste ou reporter étranger n&#039;a accès à l&#039;enclave palestinienne. Tout ce que nous savons de Gaza est raconté de l&#039;extérieur.</p><p>Pourtant, en décembre 2024, Jean-Pierre Filiu a réussi à se rendre dans la bande de Gaza pour y vivre pendant un peu plus d&#039;un mois. Il connaît intimement ce territoire, sa géographie et son peuple, dont il parle la langue. Sur place, l&#039;historien s&#039;est fait enquêteur. Il nous permet de renouer avec les humbles et les sans-grade de ce territoire abandonné du monde. Leur combat quotidien pour la survie et pour la dignité nous offre une formidable leçon d&#039;humanité, car ce qui se déroule dans cette prison à ciel ouvert a et aura une valeur universelle.</p>",
                'publication_date' => "2025-05-28",
                'isbn' => null,
                'publisher_id' => 3,
                'link' => "https://arenes.fr/livre/un-historien-a-gaza/",
                'image' => "http://atdc4.test/storage/images/books/69ac8796bed80.png",
                'created_at' => "2026-03-07 20:16:22.000",
                'updated_at' => "2026-03-07 20:16:22.000"
            ],
            [
                'id' => 6,
                'title' => "La concience juive à l'épreuve des massacres",
                'subtitle' => "Israël-Gaza",
                'authors' => "Jean-Christophe Attias, Esther Benbassa",
                'summary' => "<p>« Ce texte court, que nous avons conçu comme un examen de conscience sans concession, replace le choc du 7 octobre 2023 et de ses suites dans l’histoire longue du conflit israélo-palestinien. Il analyse nos doutes, notre situation délicate, déchirés que nous sommes entre les horreurs commises par le Hamas, notre attachement à l’éthique juive, notre rejet de la politique israélienne, notre indignation et notre douleur face au massacre commis à Gaza. Il explique aussi à quelle déception nous a exposés une partie de la gauche radicale par certaines de ses réactions. Nous sommes l’un et l’autre, comme universitaires et comme essayistes, des spécialistes reconnus de l’histoire du judaïsme et des Juifs. Nous connaissons par ailleurs personnellement aussi bien Israël que la Palestine comme réalités concrètes et vivantes. Nous avons soutenu publiquement la cause palestinienne toutes ces années, et continuons de la soutenir. »</p>",
                'publication_date' => "2024-10-02",
                'isbn' => null,
                'publisher_id' => 5,
                'link' => "https://www.editionstextuel.com/livre/la_conscience_juive_a_lepreuve_des_massacres",
                'image' => "http://atdc4.test/storage/images/books/69ac89392302c.png",
                'created_at' => "2026-03-07 20:23:21.000",
                'updated_at' => "2026-03-07 20:23:21.000"
            ],
            [
                'id' => 7,
                'title' => "Le Proche-Orient miroir du monde",
                'subtitle' => "Comprendre le basculement en cours",
                'authors' => "Ziad Majed",
                'summary' => "<p>À Gaza, un génocide est en cours, orchestré par le gouvernement de Benjamin Netanyahou, qui poursuit parallèlement une politique de nettoyage ethnique et d&#039;annexion en Cisjordanie, avec le soutien de Donald Trump et la passivité complice de la majorité des gouvernements européens.</p><p>Au Liban, la population est tiraillée entre aspirations à des réformes, menaces de nouvelles crises, occupation et attaques israéliennes dans le sud du pays. En Syrie, après quatorze années de révolution, de guerre et d&#039;interventions étrangères, le régime des Assad a été renversé, ouvrant la voie à une transition marquée par la violence dans un pays morcelé, ravagé et amputé de nouveaux territoires occupés par les Israéliens. L&#039;Iran, puissance régionale dominante depuis 2003, voit son influence vaciller à la suite des revers subis par ses alliés et d&#039;un affrontement direct avec Israël et les États-Unis.</p><p>Comment appréhender cette brutale accélération de l&#039;histoire ? En quoi les bouleversements du Proche-Orient révèlent-ils les lignes de fracture d&#039;un ordre mondial en recomposition, où logiques impériales, replis identitaires et héritages coloniaux supplantent les principes universels et les normes juridiques issus de l&#039;après-1945 ?</p><p>Cet ouvrage propose des clés de lecture pour comprendre ces transformations. À travers l&#039;examen rigoureux de huit moments fondateurs entre 1915 et 2025, il retrace un siècle de luttes, d&#039;ingérences et de reconfigurations, et rend accessible l&#039;histoire contemporaine d&#039;un Proche-Orient plus que jamais miroir du monde.</p>",
                'publication_date' => "2025-10-09",
                'isbn' => null,
                'publisher_id' => 2,
                'link' => "https://www.editionsladecouverte.fr/le_proche_orient_miroir_du_monde-9782348089732",
                'image' => null,
                'created_at' => "2026-03-07 20:25:36.000",
                'updated_at' => "2026-03-07 20:25:36.000"
            ],
            [
                'id' => 8,
                'title' => "Pour en finir avec les idées fausses sur l'Histoire de France",
                'subtitle' => null,
                'authors' => "Julien Théry, Thomas-Louis Novillo ",
                'summary' => "<p>L’histoire est sans doute la discipline la plus instrumentalisée, malmenée, détournée, arrangée, à des fins politiques le plus souvent. Julien Théry décortique une vingtaine d’idées fausses. L’occasion de revenir sur des moments clés de l’histoire de notre pays, mais aussi de faire un état des lieux de la recherche historiographique sur des questions cruciales, au centre de débats qui méritent des mises au point.</p>",
                'publication_date' => "2026-03-07",
                'isbn' => null,
                'publisher_id' => 6,
                'link' => "https://editionsatelier.com/boutique/25-en-finir-avec-les-idees-fausses",
                'image' => "http://atdc4.test/storage/images/books/69ac8a98b1512.png",
                'created_at' => "2026-03-07 20:29:12.000",
                'updated_at' => "2026-03-07 20:29:12.000"
            ],
            [
                'id' => 9,
                'title' => "La Dissolution de la Ve République",
                'subtitle' => null,
                'authors' => "Denis Baranger, Olivier Beaud",
                'summary' => "<p>La dissolution précipitée, le 9 juin 2024, de l&#039;Assemblée nationale par Emmanuel Macron a révélé une crise de régime longtemps contenue. Derrière les discours rassurants sur la robustesse de la Ve République, les signes de décomposition se multiplient depuis des années : blocages politiques, effacement du Parlement, gouvernance par décrets, rupture entre les institutions et le corps social... La fragmentation et la paralysie de la représentation nationale marquent l&#039;aboutissement d&#039;un long processus d&#039;effritement. Pour comprendre où va la Ve République, il faut revenir sur ce qu&#039;elle fut. En éclairant l&#039;actualité politique à la lumière du droit constitutionnel, cet ouvrage met au jour les causes profondes de l&#039;impasse où se débattent les acteurs de la vie politique française. Il montre comment une Constitution conçue pour stabiliser le pouvoir est devenue la source même de son instabilité.</p>",
                'publication_date' => "2026-03-07",
                'isbn' => null,
                'publisher_id' => null,
                'link' => null,
                'image' => "http://atdc4.test/storage/images/books/69ac8af8ea6cc.png",
                'created_at' => "2026-03-07 20:30:48.000",
                'updated_at' => "2026-03-07 20:30:48.000"
            ],
            [
                'id' => 10,
                'title' => "Haïti - France, les chaînes de la dette",
                'subtitle' => null,
                'authors' => "Jean-Claude Bruffarts, Marcel Dorigny, Gusti-Klara GAILLARD, Jean-Marie Théodat",
                'summary' => "<p>Par une ordonnance du roi Charles X du 17 avril 1825, la France reconnaît l’indépendance de sa colonie de Saint-Domingue. Cette reconnaissance est soumise au paiement, par la république d’Haïti, d’une somme de 150 millions de francs-or destinée à indemniser les colons français qui ont perdu les propriétés qu&#039;ils détenaient dans la colonie. En juillet 1825, accompagné d&#039;une escadre, le baron de Mackau est chargé de remettre cette ordonnance au président d&#039;Haïti, Jean-Pierre Boyer. A son retour de mission, il rédige un rapport : c&#039;est ce document exceptionnel, largement inédit, qui est au coeur de l&#039;ouvrage. Cette publication apporte un éclairage de première importance sur la « dette de l’indépendance » imposée à Haïti par l’ancienne métropole. Les chaînes qui l&#039;accompagnent sont ici abordées dans une mise en perspective de longue durée, grâce à un appareil critique et aux articles que signent les quatre coauteurs.</p>",
                'publication_date' => "2022-02-10",
                'isbn' => null,
                'publisher_id' => 7,
                'link' => null,
                'image' => "http://atdc4.test/storage/images/books/69ac8c7924c83.png",
                'created_at' => "2026-03-07 20:37:13.000",
                'updated_at' => "2026-03-07 20:37:13.000"
            ],
            [
                'id' => 11,
                'title' => "Le problème à trois corps du capitalisme",
                'subtitle' => "De l'impasse libérale-démocratique à la fuite en avant autoritaire",
                'authors' => "Romaric Godin",
                'summary' => "<p>Le capitalisme est confronté à un problème équivalent à celui à trois corps des astrophysiciens : les crises qui le minent entretiennent des interactions dont la dynamique est imprévisible, évacuant tout espoir d&#039;en maîtriser les termes. Traiter ces crises séparément nous emmène dans le mur ; prendre au sérieux leur entremêlement nous poussera vers la seule issue : la sortie.</p>",
                'publication_date' => "2026-03-07",
                'isbn' => null,
                'publisher_id' => 2,
                'link' => "https://www.babelio.com/livres/Godin-Le-probleme-a-trois-corps-du-capitalisme-De-limp/1949076",
                'image' => "http://atdc4.test/storage/images/books/69ac8d7a44142.png",
                'created_at' => "2026-03-07 20:41:30.000",
                'updated_at' => "2026-03-07 20:41:30.000"
            ],
            [
                'id' => 12,
                'title' => "Discriminations",
                'subtitle' => "Pourquoi sont elles un défi majeur des sociétés démocratiques et comment les combattre",
                'authors' => "Mirna Safi",
                'summary' => "<p>Pourquoi les discriminations, ces inégalités de traitement fondées sur des critères tels que l’origine, le genre, l’orientation sexuelle, persistent-elles dans des pays démocratiques pourtant engagés en faveur de l’égalité des chances ? Comment mesurer leur ampleur et peut-on comprendre les mécanismes qui les sous-tendent ?</p><p>À travers une synthèse rigoureuse et accessible des recherches en sciences sociales, cet ouvrage plonge au cœur de ces questions. Il expose les faits de discrimination en France et à l’international et étudie leurs manifestations dans des domaines variés – emploi, logement, éducation, vie quotidienne. Il discute aussi les moyens d’action en explorant une large palette d’instruments : législation, sensibilisation, transformation des pratiques organisationnelles, politiques de redistribution.</p><p>Un guide précieux pour décrypter l’un des enjeux les plus complexes et cruciaux des sociétés contemporaines, et pour réfléchir à des solutions concrètes à ce défi majeur des démocraties.</p>",
                'publication_date' => "2026-03-07",
                'isbn' => null,
                'publisher_id' => 8,
                'link' => "https://www.lgdj.fr/discriminations-9782130837930.html",
                'image' => "http://atdc4.test/storage/images/books/69ac8e433d496.png",
                'created_at' => "2026-03-07 20:44:51.000",
                'updated_at' => "2026-03-07 20:44:51.000"
            ],
            [
                'id' => 13,
                'title' => "Gaza, une guerre coloniale",
                'subtitle' => null,
                'authors' => "Stéphanie Latte Abdallah, Véronique Bontemps",
                'summary' => "<p>La guerre déclenchée à Gaza après le 7 octobre 2023 s&#039;inscrit dans une continuité qui n&#039;implique pas seulement la bande de Gaza mais également le reste de la Palestine historique ainsi que les sociétés alentour, de longue date concernées par l&#039;actualité palestinienne. De quoi la guerre actuelle à Gaza est-elle le nom ou l&#039;apogée ? Quels processus et quelles logiques, poussés à leur terme, sont-ils à l&#039;oeuvre dans les massacres en cours ?</p><p>Un ouvrage pluridisciplinaire, alliant analyse politique, perspectives judiciaires et historiques à des approches socio-anthropologiques, pour comprendre l&#039;histoire en train de se faire.</p>",
                'publication_date' => "2025-05-14",
                'isbn' => null,
                'publisher_id' => 9,
                'link' => "https://www.babelio.com/livres/Latte-Abdallah-Gaza-une-guerre-coloniale/1915354",
                'image' => "http://atdc4.test/storage/images/books/69ac8f2911469.png",
                'created_at' => "2026-03-07 20:48:41.000",
                'updated_at' => "2026-03-07 20:48:41.000"
            ],
            [
                'id' => 14,
                'title' => "1945 : les Français ont la parole",
                'subtitle' => "Les cahiers de doléances des États généraux de la Renaissance française",
                'authors' => "Danielle Tartakowsky",
                'summary' => "<p>En décembre 1944, le Conseil national de la Résistance décide de la tenue d’États généraux de la Renaissance française à Paris du 10 au 13 juillet. Les comités départementaux de Libération doivent préalablement organiser des assemblées communales chargées d’élaborer des « cahiers de doléances », empruntant à 1789.</p><p>Leur objectif : permettre une appropriation collective du programme du CNR, proposer à leur échelle des déclinaisons concrètes d’une « véritable démocratie économique et sociale » et s’attacher aux questions sociétales et macro-politiques qui se sont précisées ou ont émergé depuis la Libération.</p><p>Les synthèses départementales et des centaines de cahiers communaux conservés par Louis Saillant, alors président du CNR permettent une plongée dans la France de 1945 et ses aspirations.</p>",
                'publication_date' => "2025-10-17",
                'isbn' => null,
                'publisher_id' => 10,
                'link' => null,
                'image' => "http://atdc4.test/storage/images/books/69ac9069b0255.png",
                'created_at' => "2026-03-07 20:53:12.000",
                'updated_at' => "2026-03-07 20:54:01.000"
            ],
            [
                'id' => 15,
                'title' => "Découvrir Fanon",
                'subtitle' => null,
                'authors' => "Marouane Essadek",
                'summary' => "<p>Souvent évoquée, la figure de Fanon reste mal connue.  Les textes ici rassemblés montrent la richesse de son œuvre mue par une ambition constante : analyser les causes de l’oppression et lutter pour la libération des peuples. À la croisée de différents champs – antiracisme, psychiatrie, philosophie, anti-colonialisme – son œuvre fonde une pensée révolutionnaire et humaniste. Tout en contextualisant ses grandes analyses – l’expérience du racisme, la violence révolutionnaire – cet ouvrage présente aussi certains textes moins connus (la psychiatrie en contexte colonial, le dévoilement des Algériennes par l’armée française…). Comme dans le reste de la collection « Découvrir », chaque extrait est commenté et agrémenté de pistes bibliographiques « pour aller plus loin ».</p>",
                'publication_date' => "2026-03-07",
                'isbn' => null,
                'publisher_id' => 11,
                'link' => "https://editionssociales.fr/catalogue/decouvrir-fanon/",
                'image' => "http://atdc4.test/storage/images/books/69ac9115c915b.png",
                'created_at' => "2026-03-07 20:56:53.000",
                'updated_at' => "2026-03-07 20:56:53.000"
            ],
            [
                'id' => 16,
                'title' => "L'Exil, toujours recommencé",
                'subtitle' => "Chronique de la frontière",
                'authors' => "Anne-Claire Defossez, Didier Fassin",
                'summary' => "<p>Cinq années durant, Didier Fassin et Anne-Claire Defossez ont mené une recherche à la frontière entre l’Italie et la France, dans les Alpes, auprès d’hommes, de femmes et d’enfants qui ont fui les violences, les persécutions ou la pauvreté, s’engageant dans un périple de plusieurs années. Ils ont rencontré tous les acteurs impliqués dans la solidarité avec ces personnes et dans le contrôle des migrations. Leur enquête donne ainsi à comprendre l’expérience des exilés au long de leur voyage, l’engagement des volontaires qui leur portent assistance et l’impuissance des forces de l’ordre à accomplir leur mission. Elle dévoile l’inefficacité d’une politique irrespectueuse du droit qui met en danger celles et ceux qui tentent de franchir la frontière.</p>",
                'publication_date' => "2026-03-06",
                'isbn' => null,
                'publisher_id' => 12,
                'link' => "https://www.editionspoints.com/ouvrage/l-exil-toujours-recommence-didier-fassin/9791041426706",
                'image' => "http://atdc4.test/storage/images/books/69ac91bedcd1a.png",
                'created_at' => "2026-03-07 20:59:42.000",
                'updated_at' => "2026-03-07 20:59:42.000"
            ],
            [
                'id' => 17,
                'title' => "L'ère de la post-vérité",
                'subtitle' => "Comment les algorithmes changent notre rapport à la réalité",
                'authors' => "Michaël Lainé",
                'summary' => "<p>À une époque où tout un chacun se réclame de la raison, le monde semble avoir perdu la tête, des États-Unis à l&#039;Argentine en passant par l&#039;Europe. Non seulement les individus peinent à discerner le vrai du faux, mais ils valorisent moins la vérité. Préférant les opinions préconçues et les fictions à la science, ils prennent de plus en plus leurs fantasmes et leurs peurs pour des réalités. Partout, les sociétés se polarisent.</p><p>Fruit de trois ans de recherche pluridisciplinaire, cet ouvrage est le premier à caractériser scientifiquement la post-vérité et à en explorer toutes les dimensions, bien au-delà des &quot; infox &quot; auxquelles on la réduit abusivement. Dans une approche mêlant psychologie, neurosciences et économie des émotions, il montre les effets dévastateurs d&#039;Internet et des réseaux sociaux, dont les algorithmes privilégient les contenus clivants et anxiogènes tout en confortant les croyances préalables. Ainsi se forment de dangereuses &quot; bulles cognitives &quot;.</p><p>Le diagnostic est sans appel : ce basculement progressif des mentalités est intimement lié au capitalisme. Pour générer un maximum de revenus publicitaires, les algorithmes s&#039;adressent à la part de nous-même qui souhaite se débarrasser de la réalité. Et s&#039;ils instauraient la plus insidieuse des servitudes volontaires, avec notre complicité inconsciente ? Cet essai démontre aussi que l&#039;essor mondial des extrêmes droites est en grande partie dû aux biais d&#039;Internet et des réseaux sociaux, qui en favorisent les idées. Un livre salutaire qui invite à un sursaut de lucidité face à un enjeu social majeur de ce siècle.</p>",
                'publication_date' => "2025-05-07",
                'isbn' => null,
                'publisher_id' => 2,
                'link' => "https://www.editionsladecouverte.fr/l_ere_de_la_post_verite-9782348088438",
                'image' => "http://atdc4.test/storage/images/books/69ac9250504a0.png",
                'created_at' => "2026-03-07 21:02:08.000",
                'updated_at' => "2026-03-07 21:02:08.000"
            ],
            [
                'id' => 18,
                'title' => "L'espace public éclaté",
                'subtitle' => null,
                'authors' => "Éric Dacheux",
                'summary' => "<p>Pas de démocratie sans espace public. Ce dernier, dans la Grèce antique, était un espace physique local (l’agora) où se regroupaient les citoyens pour décider ensemble de la vie de la cité. C’est, aujourd’hui, un espace symbolique ouvert à l’international où se confrontent les acteurs politiques, les médias, les réseaux sociaux etc., en vue de contribuer à élaborer l’opinion publique. Ainsi, comprendre l’espace public, c’est expliquer la société démocratique dans laquelle nous vivons. C’est pourquoi l’objectif de cet ouvrage collectif est d’en cerner les évolutions récentes. Or loin de s’unifier sous la pression technologique, l’espace public se fragmente en raison de logiques sociales et culturelles diverses. Puisse cet « Essentiel » permettre au lectorat de prendre ses distances critiques avec les visions simplistes de l’espace public, cœur de nos sociétés.</p>",
                'publication_date' => "2026-03-07",
                'isbn' => null,
                'publisher_id' => 13,
                'link' => "https://www.cnrseditions.fr/catalogue/revues/l-espace-public-eclate/",
                'image' => "http://atdc4.test/storage/images/books/69ac93406d2ca.png",
                'created_at' => "2026-03-07 21:06:08.000",
                'updated_at' => "2026-03-07 21:06:08.000"
            ],
            [
                'id' => 19,
                'title' => "Collaborations",
                'subtitle' => "Enquête sur l'extrême droite et les milieux d'affaires",
                'authors' => "Laurent Mauduit",
                'summary' => "<p>L&#039;extrême droite est aux portes du pouvoir et le patronat français, loin de s&#039;opposer à cette issue, se prépare à collaborer avec elle. Enquête inédite sur ces complicités idéologiques et financières et comment certains milieux d&#039;affaires – des hautes sphères du CAC40 aux simples PME – œuvrent, ou se résolvent avec enthousiasme, à l&#039;ascension d&#039;un pouvoir toujours plus autoritaire et ultralibéral.</p><p>Une partie des élites économiques françaises tisse depuis quelques années des liens avec l&#039;extrême droite, jusqu&#039;à s&#039;y rallier parfois ouvertement. Depuis la dissolution de l&#039;Assemblée en juin 2024, ce mouvement s&#039;accélère : des chefs d&#039;entreprise, grands et petits, renoncent au &quot; barrage républicain &quot; et se préparent à collaborer avec le RN et ses alliés.</p><p>Laurent Mauduit lève le voile sur ces complicités qui, discrètes hier encore, sont aujourd&#039;hui de plus en plus souvent assumées. Rencontres en coulisse, alliances d&#039;intérêts, fascination pour le capitalisme autoritaire et libertarien promu par Trump, Musk ou Milei... L&#039;auteur décrypte cette dynamique inquiétante où les milieux d&#039;affaires trouvent dans l&#039;extrême droite une opportunité pour imposer leur agenda.</p><p>Si les positions de Bernard Arnault, Charles Beigbeder, Vincent Bolloré ou Pierre-Édouard Stérin, sont désormais publiques, nombre d&#039;autres patrons, plus discrets, mus par des intérêts purement mercantiles, leur emboîtent le pas et participent aujourd&#039;hui activement à la montée d&#039;un projet politique raciste et liberticide.</p><p>Dans cette enquête inédite, Laurent Mauduit nous entraîne des salons feutrés de l&#039;Ouest parisien, où évoluent les grands patrons, jusqu&#039;aux PME de province, dévoilant un processus en cours qui fait écho aux heures les plus sombres de notre histoire. Comment ne pas penser, comme le montre l&#039;auteur, aux années 1930, lorsque le patronat, déjà, jouait un rôle majeur dans l&#039;accession au pouvoir des régimes fascistes et nazi ? Aujourd&#039;hui, alors que le capitalisme traverse une crise prolongée, les milieux d&#039;affaires sont à nouveau des acteurs pleinement engagés dans la montée de l&#039;extrême droite.</p>",
                'publication_date' => "2025-09-11",
                'isbn' => null,
                'publisher_id' => 2,
                'link' => "https://www.editionsladecouverte.fr/collaborations_la_nouvelle_enquete_de_laurent_mauduit-9782348087073",
                'image' => "http://atdc4.test/storage/images/books/69ac93d0160cf.png",
                'created_at' => "2026-03-07 21:08:32.000",
                'updated_at' => "2026-03-07 21:08:32.000"
            ],
            [
                'id' => 20,
                'title' => "L'antiracisme trahi",
                'subtitle' => "Défense de l'universel",
                'authors' => "Florian Gulli",
                'summary' => "<p>À gauche, l’antiracisme est considéré comme un principe fondamental. Pourtant ces dernières années sa définition a volé en éclats. Un antiracisme dit « politique » a envahi la sphère médiatique et académique, et trouvé un écho important auprès de secteurs militants. Mettant en avant des concepts controversés(« blanchité », « privilège blanc »…), il condamne sans détour ce qui serait un antiracisme universaliste dépassé et déconnecté des nouvelles réalités. Critique de ces approches, le présent ouvrage entend proposer une approche de l’antiracisme qui puise ses racines dans l’histoire du mouvement ouvrier, du socialisme, et du républicanisme. Une approche souvent caricaturée et méconnue, et qui offre pourtant une grande richesse d’analyse permettant l’action. Soit un antiracisme qui retrouve véritablement le chemin de l’émancipation, loin des différentialismes de toute sorte.</p>",
                'publication_date' => "2022-09-07",
                'isbn' => null,
                'publisher_id' => 8,
                'link' => "https://www.puf.com/lantiracisme-trahi",
                'image' => "http://atdc4.test/storage/images/books/69adb7d60e3cf.png",
                'created_at' => "2026-03-08 17:54:30.000",
                'updated_at' => "2026-03-08 17:54:30.000"
            ],
            [
                'id' => 21,
                'title' => "Décoloniser la Kanaky-Nouvelle-Calédonie",
                'subtitle' => null,
                'authors' => "Benoit Trépied",
                'summary' => "<p>Le 13 mai 2024, la Kanaky-Nouvelle-Calédonie a connu un embrasement sans précédent qui fera date. Les dégâts humains, matériels et politiques ont été considérables. Mais surtout, un processus de décolonisation unique dans l’histoire a été brutalement interrompu. Ce livre voudrait fournir les clés pour comprendre un tel bouleversement.</p>",
                'publication_date' => "2025-03-01",
                'isbn' => null,
                'publisher_id' => 14,
                'link' => "https://www.editions-anacharsis.com/Decoloniser-la-Kanaky-Nouvelle-Caledonie",
                'image' => "http://atdc4.test/storage/images/books/69adbaa3b3e54.png",
                'created_at' => "2026-03-08 18:06:27.000",
                'updated_at' => "2026-03-08 18:06:27.000"
            ],
            [
                'id' => 22,
                'title' => "La machine à gagner",
                'subtitle' => "Révélations sur le RN en marche vers l’Elysée",
                'authors' => "Tristan BERTELOOT",
                'summary' => "<p>Depuis treize ans, le Front national, devenu le Rassemblement national, a conçu une stratégie de conquête du pouvoir, qu’il applique à la lettre et presque sans encombre. La formation lepéniste n’a pas obtenu la majorité absolue à l’Assemblée en 2024 comme elle l’espérait ? Qu’importe, elle a presque doublé le nombre de ses députés. Ils sont passés en moins de trois ans de 7 à 88, puis à 126, 142 si l’on additionne ses nouveaux ralliés issus des bancs des Républicains. Le RN ne compte pas s’arrêter là. Car Marine Le Pen vise l’Élysée. Et une victoire sèche et incontestable en 2027.</p>",
                'publication_date' => "2024-09-13",
                'isbn' => null,
                'publisher_id' => 15,
                'link' => "https://www.seuil.com/ouvrage/la-machine-a-gagner-tristan-berteloot/9782021539660",
                'image' => "http://atdc4.test/storage/images/books/69adbc1db7bd1.png",
                'created_at' => "2026-03-08 18:11:57.000",
                'updated_at' => "2026-03-08 18:12:45.000"
            ],
            [
                'id' => 23,
                'title' => "De l’invisibilité à la visibilité",
                'subtitle' => "Visage(s) de l’inconvenant",
                'authors' => " Christine Dualé et Anne Garrait-Bourrier",
                'summary' => "<p>Le concept de « visagéité », défini par Gilles Deleuze et Félix Guattari, est un préalable essentiel à toute analyse des stratégies d’extraction du sujet en dehors des normes. Cette notion a d’ailleurs été créée dans le but précis de questionner les rapports du sujet au corps et donc à l’identité. Audacieux, étrange et dérangeant, le rapport entre « inconvenant » et « décentrement » souligne combien les littératures et productions culturelles sortant du cadre et de l’ordre établi dérangent et bousculent les standards. Les travaux réunis dans le présent ouvrage s’attachent à analyser les stratégies de « remise à l’ordre » ou de « retour au centre » qui ont été déployées pour faire rentrer dans le rang du convenu, du convenable et de la visagéité, les créateurs même de l’inconvenant. « L’invisibilité et la visibilité » sont étudiées au prisme de « la visagéité de l’inconvenant » dans le domaine des arts (peinture, cinéma, danse), de la littérature, des relations interculturelles et de la ruralité et scrutent avec minutie les représentations protéiformes que peut recouvrir l’inconvenant.</p>",
                'publication_date' => "2026-03-09",
                'isbn' => null,
                'publisher_id' => 16,
                'link' => "https://books.openedition.org/pubp/8971",
                'image' => "http://atdc4.test/storage/images/books/69ae8745b0a07.png",
                'created_at' => "2026-03-09 08:39:33.000",
                'updated_at' => "2026-03-09 08:39:33.000"
            ],
            [
                'id' => 24,
                'title' => "Pop fascisme",
                'subtitle' => "Comment l'extrême droite a gagné la bataille culturelle sur Internet",
                'authors' => "Pierre Plottu, Maxime Macé",
                'summary' => "<p>« Grand remplacement », « immigrationnisme », « bataille de civilisation »... Les mots de l’extrême droite, et par là ses obsessions racistes, ont envahi les débats politique et médiatique grâce à un intense combat mené par la fachosphère et ses troufions sur Internet. Cet écosystème coordonné, pensé et interconnecté a permis à ces « idées » de se répandre jusque dans les médias, avec l’appui de Bolloré et de ses sbires littéralement en croisade. Combien de vues se transforment en voix pour le Rassemblement national ? Comment en est-on arrivé là ? Plongée dans le « pop fascisme », cette extrême-droitisation des esprits qui joue avec les codes de la culture populaire en ligne et infiltre l’époque.</p>",
                'publication_date' => "2024-09-27",
                'isbn' => null,
                'publisher_id' => 17,
                'link' => "https://www.editionsdivergences.com/livre/pop-fascisme",
                'image' => "http://atdc4.test/storage/images/books/69ae882213624.png",
                'created_at' => "2026-03-09 08:42:52.000",
                'updated_at' => "2026-03-09 08:43:14.000"
            ],
            [
                'id' => 25,
                'title' => "Barbarie numérique",
                'subtitle' => "une autre histoire du monde connecté",
                'authors' => "Fabien Lebrun",
                'summary' => "<p>Une enquête implacable sur la tragédie que vit le Congo, cœur des industries numériques et objet de toutes les convoitises.</p><p>À partir des années 1990, l’explosion de la production de biens électroniques, caractéristique du passage du capitalisme à son stade numérique, déclenche une guerre des métaux technologiques au Congo (RDC) qui n’a fait que gagner en intensité. Cette enquête fouillée montre que la dématérialisation est bel et bien un mythe.</p><p>Elle se nourrit d’un extractivisme sans limites dans des régions, comme celle des Grands Lacs en Afrique, qui subissent depuis des siècles les ravages de la mondialisation : de la traite négrière à la terreur coloniale du roi belge Léopold II (pour le « caoutchouc rouge » nécessaire à l’industrie automobile) jusqu’aux minerais de sang actuels (dont le coltan, essentiel aux smartphones, et le cobalt, pour la transition énergétique).</p><p>La civilisation de l’écran est synonyme d’une barbarie numérique qui se manifeste au Congo par : une économie militarisée et une criminalité institutionnalisée, un pillage généralisé, du travail forcé, le viol comme arme de guerre, la destruction des forêts et l’anéantissement de la biodiversité… Autant de catastrophes qui font du Congo l’une des plus grandes tragédies de l’histoire contemporaine, le prix fort à payer pour un monde connecté.</p>",
                'publication_date' => "2024-10-04",
                'isbn' => null,
                'publisher_id' => 18,
                'link' => "https://www.lechappee.org/collections/pour-en-finir-avec/barbarie-numerique",
                'image' => "http://atdc4.test/storage/images/books/69ae88cbd3489.png",
                'created_at' => "2026-03-09 08:46:03.000",
                'updated_at' => "2026-03-09 08:46:03.000"
            ],
            [
                'id' => 26,
                'title' => "De Paris à Hébron",
                'subtitle' => null,
                'authors' => "Chantal Abu Eisheh",
                'summary' => "<p>Chantal et Anwar. Une Française née dans le Nord de la France, un Palestinien originaire d&#039;Hébron, au sud de la Palestine ; un couple, formé en 1980, parents de deux enfants. Lui s&#039;est fait connaître au fil d&#039;un parcours remarquable - militant palestinien réfugié en 1978 en France, où il poursuit des études de droit, un temps chauffeur de taxi pour gagner sa vie, il…</p><p>Chantal et Anwar. Une Française née dans le Nord de la France, un Palestinien originaire d&#039;Hébron, au sud de la Palestine ; un couple, formé en 1980, parents de deux enfants. Lui s&#039;est fait connaître au fil d&#039;un parcours remarquable - militant palestinien réfugié en 1978 en France, où il poursuit des études de droit, un temps chauffeur de taxi pour gagner sa vie, il se voit proposer, après les accords d&#039;Oslo de 1993, un poste de professeur de droit civil à l&#039;université Al-Quds de Jérusalem-Est.</p><p>Il deviendra, en 2013-2014, ministre de la Culture de l&#039;Autorité palestinienne, et demeure l&#039;une des voix palestiniennes pacifistes majeures sur la scène internationale. Mais que sait-on du parcours de son épouse Chantal - hormis qu&#039;elle a cofondé avec lui l&#039;association d&#039;échanges culturels Hébron-France - et de son quotidien, à cheval entre deux cultures à mille lieues l&#039;une de l&#039;autre, entre la paix et la guerre, depuis qu&#039;elle a choisi d&#039;abandonner son confortable quotidien en France pour suivre Anwar et vivre à Hébron ? &quot;Depuis leur adolescence, nos enfants, issus de notre couple franco- palestinien, me disent souvent : &quot;Comment t&#039;as fait ? Raconte ! &quot; Vingt- quatre ans après mon installation en Palestine, mettre en perspective mes expériences à une époque où les questions sur l&#039;identité, la laïcité, l&#039;islamisme ou le racisme sont au centre des débats, voilà ce qui me tient à coeur depuis de longues années&quot;.</p>",
                'publication_date' => "2026-03-09",
                'isbn' => null,
                'publisher_id' => 7,
                'link' => "https://www.hemisphereseditions.com/anciennes-parutions/de-paris-%C3%A0-h%C3%A9bron",
                'image' => "http://atdc4.test/storage/images/books/69ae898aa174c.png",
                'created_at' => "2026-03-09 08:49:14.000",
                'updated_at' => "2026-03-09 08:49:14.000"
            ],
            [
                'id' => 27,
                'title' => "La machine à détruire",
                'subtitle' => "Pourquoi il faut en finir avec la finance",
                'authors' => "Aline Fares",
                'summary' => "<p>Les crises financières se succèdent et se ressemblent. Chaque fois, pour éviter le chaos, les États et les banques centrales interviennent. Mais que sauvent-ils ? Quel rapport cela a-t-il avec l’augmentation rapide des inégalités et de l’endettement des États, avec la dégradation des services publics, ou encore avec les résistances à travers le monde ?</p><p>La Machine à détruire revient sur ces crises et ce qui les suit, et s’interroge sur la place croissante des banques et de la finance dans nos existences. Suffira-t-il de déplacer l’argent vers des investissements plus verts ? Les solutions financières sont-elles à la hauteur de leurs promesses ? Peut-on se permettre de laisser les banques au centre du système ?</p><p>Loin de nous écraser avec des notions techniques et lointaines, Aline Fares et Jérémy Van Houtte proposent plutôt un regard limpide et des analyses drôles et documentées sur la finance, à partir d’expériences familières et vécues.</p>",
                'publication_date' => "2024-06-07",
                'isbn' => null,
                'publisher_id' => 15,
                'link' => "https://www.seuil.com/ouvrage/la-machine-a-detruire-aline-fares/9782021536874",
                'image' => "http://atdc4.test/storage/images/books/69ae8a588059e.png",
                'created_at' => "2026-03-09 08:52:40.000",
                'updated_at' => "2026-03-09 08:52:40.000"
            ],
            [
                'id' => 28,
                'title' => "Parias",
                'subtitle' => "Hannah Arendt et la « tribu » en France (1933-1941)",
                'authors' => "Marina Touilliez",
                'summary' => "<p>Fuyant la Gestapo, Hannah Arendt arrive à Paris en octobre 1933. La jeune femme de 27 ans, promise à une brillante carrière universitaire en Allemagne, doit se faire aux chambres insalubres des hôtels garnis, à la difficulté de trouver du travail et à l’hostilité d’une partie des Français.</p><p>Mais dans le quartier latin et à Montparnasse, ceux qui ont fui Hitler parviennent à faire vivre un autre pays en exil. Elle y croise Heinrich Blücher, faux dandy et vrai révolutionnaire, qui deviendra son mari. Tous deux font partie d’une famille d’hurluberlus magnifiques – composée, entre autres, d’Erich Cohn-Bendit, Lotte Sempell, Chanan Klenbort, Adrienne Monnier, Fritz Fränkel, Minna Flake et Arthur Koestler – qui se retrouvent autour du génial Walter Benjamin. Ils forment cette « tribu » qui donne à chacun la force de continuer à vivre.</p><p>À l’approche de la guerre, et face à l’afflux de réfugiés, l’administration française interne les « indésirables » et les amis sont l’un après l’autre enfermés. Pendant plusieurs semaines, Arendt connaît « l’enfer du camp de Gurs » et frôle le désespoir. Lorsque les troupes nazies envahissent la France, elle profite du chaos pour fuir le camp… Fruit d’une enquête minutieuse, réalisée notamment à partir d’archives et de témoignages inédits, voici le récit palpitant des huit années françaises de Hannah Arendt qui marqueront profondément sa vie et son œuvre.</p>",
                'publication_date' => "2024-10-04",
                'isbn' => null,
                'publisher_id' => 18,
                'link' => "https://www.lechappee.org/collections/hors-collection/parias",
                'image' => "http://atdc4.test/storage/images/books/69ae8b0072fb4.png",
                'created_at' => "2026-03-09 08:55:28.000",
                'updated_at' => "2026-03-09 08:55:28.000"
            ],
            [
                'id' => 29,
                'title' => "Le massacre de Thiaroye",
                'subtitle' => "Histoire d’un mensonge d’État",
                'authors' => "Armelle Mabon",
                'summary' => "<p>1er décembre 1944, camp de Thiaroye, en périphérie de Dakar. Des tirailleurs sénégalais, faits prisonniers par les Allemands lors de la guerre et récemment rapatriés, réclament le paiement de leur solde. Un droit qui leur était promis depuis des mois. La réponse est sanglante et d’une violence inouïe : des centaines d’entre eux sont rassemblés sur une esplanade du camp, froidement mitraillés puis jetés dans des fosses communes.</p><p>Pourtant, dès le lendemain, les autorités coloniales et militaires prétexteront une rébellion armée des tirailleurs et feront état de trente-cinq morts. Entre mensonge d’État et fraude scientifique, l’historienne Armelle Mabon mène depuis dix ans un véritable combat pour réhabiliter ces hommes et les faire reconnaître comme victimes d’un crime d’État.</p><p>À l’heure des commémorations pour les quatre-vingts ans de ce massacre, ce livre est d’autant plus nécessaire que la France s’obstine à refuser de regarder en face l’héritage raciste de la colonisation.</p>",
                'publication_date' => "2026-03-09",
                'isbn' => null,
                'publisher_id' => 19,
                'link' => "https://www.lepassagerclandestin.fr/catalogue/essais/le-massacre-de-thiaroye/",
                'image' => "http://atdc4.test/storage/images/books/69ae8bc615f40.png",
                'created_at' => "2026-03-09 08:58:46.000",
                'updated_at' => "2026-03-09 08:58:46.000"
            ],
            [
                'id' => 30,
                'title' => "Théorie délibérative des valeurs",
                'subtitle' => "De la valeur travail à un travail sur les valeurs",
                'authors' => " Éric Dacheux, Daniel Goujon",
                'summary' => "<p>« Tout ce qui a son prix est de peu de valeur », affirmait Nietzsche. Pourtant, aujourd’hui, tout se passe comme si la valeur économique résumait les valeurs de notre société pour être la seule mesure du bien-être. Cette domination nous place devant une triple crise : écologique, démocratique et économique. Écologique car la valeur économique ne permet pas de prendre en compte la complexité du vivant. Démocratique car les débats politiques sont soumis aux lois de la valeur économique ce qui oriente le débat, légitime les inégalités et interdit une remise en cause radicale du mode de vie. Économique parce que la création de valeur repose aujourd’hui encore sur le besoin d’une croissance infinie sur une planète finie. Ainsi, ouvrir le débat sur les valeurs, c’est se donner les moyens de penser le monde de demain. Un monde écologique nécessite de passer de la suprématie de la valeur travail à un travail démocratique sur les valeurs. À condition cependant de sortir de nos démocraties représentatives à bout de souffle pour emprunter la voie de la participation et de la délibération. Dans cette perspective délibérative, il n’y a pas de valeur qui échappe au débat collectif : ce qui constitue le vivre ensemble est un choix de société. Ainsi, le bien-être n’est pas une affirmation universelle et intemporelle mais une interrogation permanente : à quoi tenons-nous ?</p>",
                'publication_date' => "2024-09-18",
                'isbn' => null,
                'publisher_id' => 20,
                'link' => "https://presses-universitaires.univ-amu.fr/fr/actualites/theorie-deliberative-valeurs",
                'image' => "http://atdc4.test/storage/images/books/69ae8cc3625e9.png",
                'created_at' => "2026-03-09 09:02:59.000",
                'updated_at' => "2026-03-09 09:02:59.000"
            ],
        ]);
    }
}
